spring:
  application:
      name: product
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.12.84:3307/SpringCloud_practice?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: 192.168.12.84
    port: 5672
    password: guest
    username: guest
  redis:
    host: 192.168.12.84
    port: 6397
env:
  dev

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'