spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/SpringCloud_practice?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # jpa:
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  redis:
    host: localhost
    port: 6397
env:
  dev

mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
  mapper-locations: classpath:/mapper/*.xml

server:
  port: 9401

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'